### ISSUE TITLE
github pagesのURLがなんかおかしい

### ISSUE THREAD

**Issue by prism-kumamoto-u** [prism-kumamoto-u/prism-kumamoto-u.github.io#1]
リンクが
https://prism-kumamoto-u.github.io/prism-kumamoto-u.gihub.io/
となっていて、usernameが繰り返されている。
このためにページが正常に表示されない。

**Comment by Ken3-K** [comment]
レポジトリ名がgihubと、tが抜けていたからと判明。修正済み
